elasticsearch:
  auth:
    enabled: false
    user: null
    password: null
    existingSecret:
      name: null
      key: null
  includeTagKey: true
  setOutputHostEnvVar: true
  # If setOutputHostEnvVar is false this value is ignored
  #hosts: ["elasticsearch-client:9200"]
  hosts: ["elasticsearch-master.logging-efk.svc.cluster.local:9200"]